# Generated by Django 4.1.5 on 2023-03-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_article_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='s',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='deneme'),
        ),
    ]
