# Generated by Django 4.1.5 on 2023-03-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_article_s'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='s',
        ),
        migrations.AlterField(
            model_name='article',
            name='read_time',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Okuma Süresi'),
        ),
    ]
