# Generated by Django 4.1.6 on 2023-03-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0004_remove_article_s_alter_article_read_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='s',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='deneme tarih'),
        ),
    ]
