# Generated by Django 4.1.6 on 2023-03-23 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0005_article_s'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='s',
        ),
    ]
