# Generated by Django 4.1.6 on 2023-03-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0007_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subject',
            field=models.CharField(max_length=100, null=True, verbose_name='Makale Konu'),
        ),
    ]
